name: Deploy Javadoc
description: "Automatically  generate your Javadoc from your maven project and deploy it with GitHub Page on javadoc branch."
branding:
  icon: "book-open"
  color: "white"
inputs:

  # Required inputs

  java-version: # version of java
    description: "Java version inside your project"
    required: true
    default: "17"
    type: string
  GITHUB_TOKEN: # GitHub Token
    description: "The GitHub token the GitHub repository"
    required: true
  javadoc-branch: # branch where the javadoc is hosted
    description: "Branch where the javadoc is hosted"
    required: true
    default: javadoc
    type: string
  target-folder: # target folder for the javadoc contents
    description: "Directory where the javadoc contents should be stored"
    required: true
    default: .
    type: string

  # Optional inputs

  java-distribution: # distribution of java
    description: "Java distribution inside your project"
    required: false
    default: "adopt"


  # Used for development and testing :

  without-deploy: # deploy the javadoc to the GitHub Page, is used for development testing with nektos/act
    description: "Enable or disable deploy of the javadoc to the GitHub Page"
    required: false
    default: "false"
    type: boolean
  without-checkout: # checkout the javadoc branch, is used for development testing with nektos/act
    description: "Enable or disable the checkout"
    required: false
    default: "false"
    type: boolean

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      if: inputs.without-checkout == 'false'
      with:
        fetch-depth: 0

    - uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.java-distribution }}

    - name: Generate Javadoc
      run: mvn org.apache.maven.plugins:maven-javadoc-plugin:3.4.0:aggregate
      shell: bash

    - name: Deploy 🚀
      if: ${{ inputs.without-deploy == 'false' }}
      uses: JamesIves/github-pages-deploy-action@v4.4.0
      with:
        token: ${{ inputs.GITHUB_TOKEN }}
        branch: ${{ inputs.javadoc-branch }}
        clean: true
        folder: target/site/apidocs
        target-folder: ${{ inputs.target-folder }}
