name: Test Actions

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]
    
    name: Test with Java ${{ matrix.java }}
    steps:
    
      - uses: actions/checkout@v3
      - uses: ./ # Uses an action in the root directory
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: javadoc-test
          java-version: ${{ matrix.java }}
          target-folder: javadoc
          without-deploy: true

      - uses: GuillaumeFalourd/assert-command-line-output@v2
        with:
          command_line: cat target/site/apidocs/index.html
          contains: javadoc
    
